{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.ambient.crossdevice",
    "module": "crossdevice",
    "version": "0.1.0-preview01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "crossdevice-0.1.0-preview01.aar",
          "url": "crossdevice-0.1.0-preview01.aar",
          "size": 467985,
          "sha512": "ce91b095fbe067b097a2d5d1648d444929d3c751079ceda1755d6aec5f350dbdcd380dc21264c0a627e4f4ee0105eb014bcc61ae02a73a851fa95d31e2894e64",
          "sha256": "ec8f56a0e63040755e3cc64c21df6d855ef8c55ac9a87d7a64da602a8c4da9eb",
          "sha1": "b899629d927ceb105280542ab3d6d4f3372857e4",
          "md5": "a1ee7dc37457fa8690239da807fd118f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-nearby",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-dtdi",
          "version": {
            "requires": "16.0.0-beta01"
          }
        },
        {
          "group": "com.google.android.datatransport",
          "module": "transport-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.android.datatransport",
          "module": "transport-runtime",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.google.android.datatransport",
          "module": "transport-backend-cct",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.21.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "crossdevice-0.1.0-preview01.aar",
          "url": "crossdevice-0.1.0-preview01.aar",
          "size": 467985,
          "sha512": "ce91b095fbe067b097a2d5d1648d444929d3c751079ceda1755d6aec5f350dbdcd380dc21264c0a627e4f4ee0105eb014bcc61ae02a73a851fa95d31e2894e64",
          "sha256": "ec8f56a0e63040755e3cc64c21df6d855ef8c55ac9a87d7a64da602a8c4da9eb",
          "sha1": "b899629d927ceb105280542ab3d6d4f3372857e4",
          "md5": "a1ee7dc37457fa8690239da807fd118f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crossdevice-0.1.0-preview01-sources.jar",
          "url": "crossdevice-0.1.0-preview01-sources.jar",
          "size": 83935,
          "sha512": "740ce31fd99a1cad8dafd29effff36e35bd1afa21eb217dec5a590a02da829878561ecfbfd78b9b64f454cc0402fd3c5639cec73e1c6755d831ec22a6eee324c",
          "sha256": "cbe71671df4220feb161725381c19a18a1dd5096ef600348316141890cb3756e",
          "sha1": "96be2850490a6e157c779905c5c767721e208383",
          "md5": "88b8dfbdef393537182471f8576c102c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crossdevice-0.1.0-preview01-javadoc.jar",
          "url": "crossdevice-0.1.0-preview01-javadoc.jar",
          "size": 481515,
          "sha512": "53f7d54b6508f269361566a5e42d8983bbf6282154987a95d5fadabb43e2df0aa2d18de1fde9e5c8cf002abecb488b5e842146708d77e526a65506c5dbd0b91e",
          "sha256": "a46494d9ce568f35b5652a7bee950fe06803377f58a95cbc347b94fe3fff2625",
          "sha1": "7b631c8f702a5196cede9c44038bbfa2f8c932a4",
          "md5": "c84f34bff459eb1dc26fa9e56cc57309"
        }
      ]
    }
  ]
}
